server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/globalmed?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: mes_user
    password: mes_pwd
  jpa:
    hibernate:
      ddl-auto: validate           # 운영스럽게 validate(개발 중 create/update 쓰고 싶으면 팀 합의)
    properties:
      hibernate:
        jdbc:
          time_zone: UTC           # DB-UTC 일치
          serialization:
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    root: INFO
app:
  security:
    jwt:
      secret: 0123456789abcdef0123456789abcdef
      ttl-minutes: 30